baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = "Rong's wiki"
theme = 'FixIt'
defaultContentLanguage = 'zh-cn'

[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"

[params.math]
  enable = true
  copyTex = true
